name: Example Workflow

on:
  push:
    branches: ['dev']

  workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:

      - name: Say Hello
        run: |
          echo Hello!

      - name: Look Around
        run: |
          echo '$pwd'
          pwd
          echo '$ ls -la'
          ls -la

      - name: Say Goodbye
        run:    |
          echo Goodbye!            
