name: Example Workflow

on:
    workflow_dispatch:

jobs:
    example_job:
        runs-on: ubuntu-latest
        steps:

            - name: Say Hello
                run: |
                    echo Hello!

            - name: Say Goodbye
                run: |
                    echo Goodbye!            